---
- hosts: k8s_master
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
           file: ../../vars.yml

      - name: Deploying MetalLB.
        become: yes
        shell: kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml

      - name: Configuring MetalLB.
        become: yes
        shell: echo "{{ lookup('template', '../../files/templates/MetalLB/cm_metallb.yml.j2') }}" | kubectl create -f -
