---
- import_playbook: playbooks/main/deploy_qcow2_vms.yml
- import_playbook: playbooks/main/install_base_packages.yml
- import_playbook: playbooks/main/install_base_packages_local.yml
- import_playbook: playbooks/main/bootstrap_kubernetes.yml
- import_playbook: playbooks/optional/deploy_metallb.yml
- import_playbook: playbooks/optional/deploy_ingress_nginx_controller.yml
